### ISSUE TITLE
Vague error if 'platform' value is missing in platform section and inspec profile platfrom/os-family is set

### ISSUE THREAD

**Issue by nvtkaszpir** [chef/kitchen-inspec#101]
# General info

My inspec profile had platform set to 'all'', while my platform section for debian7 did not specify 'platform' value at all. But on the other hand inspec profile has os-family set.

Thus, when invoking kitchen verify I got error like below:

``` bash
Failed to complete #verify action: [no implicit conversion of nil into Array]
```

backtrace goes to `/home/kaszpir/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/kitchen-inspec-0.15.0/lib/kitchen/verifier/inspec.rb:133:in `+'`

where line 133 shows:

``` ruby
(local_suite_files + config[:inspec_tests]).compact
```

After adding some debugging messages I have found out that `config[:inspec_tests]` is `nil`

Then I verified platform on inspec profile and in kitchen.yml  and they were different (well, actually platfrom was not set for debian in my case)
# Steps to reproduce

I believe you can reproduce it with any driver, below is with LXC, also provisioner is rahter not important here.

Proper kitchen.yml - see comments

``` yaml

---
driver_plugin: lxc

driver:
  name: vagrant
  provider: lxc

transport:
  name: sftp # kitchen-sync does not work properly with test-kitchen 1.4.x
  compression_level: 9

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_config_path: puppet/hiera.kitchen.yaml # different file mapping than files uploaded by boilerplate
  hiera_data_path: puppet/hiera
  puppet_verbose: true
  require_chef_for_busser: false

verifier:
  name: inspec

platforms:
# https://github.com/fgrehm/vagrant-lxc-base-boxes
# vagrant box add --name debian7lxc --provider lxc vagrant-lxc-wheezy-amd64.box

- name: debian.7-lxc
  platform: debian # without this line it breaks with error [no implicit conversion of nil into Array], so comment this line to the the error for free! :)
  driver:
    box: debian7lxc
  driver_config:
    username: root
    password: root

suites:
  - name: twemproxy
    driver:
    provisioner:
      manifest: twemproxy.pp
    verifier:
      inspec_tests:
        - inspec/twemproxy
```

inspec file:

``` yaml
name: twemproxy
title: InSpec Profile
maintainer: Michał Sochoń
copyright: Michał Sochoń
copyright_email: kaszpir@gmail.com
license: Apache 2 license
summary: An InSpec Profile for twemproxy node
version: 0.2.0
supports:
  - os-family: debian
    release: 7
  - platform: all
```
# More info

Test Kitchen version 1.11.1
inspec version 0.32.0
kitchen-inspec (0.15.0)
# Fix

Generate more sane message if test suite list is empty.
