### ISSUE TITLE
Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.

### ISSUE THREAD

**Issue by TheNotary** [chef/kitchen-inspec#105]
I'm having trouble running the tests for a chef cookbook.  I've resolved many errors, but this one finally stumped me.  

```
$ kitchen test
-----> Starting Kitchen (v1.13.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

(.kitchen.yml)
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.04
    driver_config:
      box: opscode-ubuntu-15.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-15.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[my_hostname::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
```

```
$ chef -v && kitchen -v && chef gem list inspec
Chef Development Kit Version: 0.18.30
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: ERROR

Test Kitchen version 1.13.2

*** LOCAL GEMS ***
debug_inspector (0.0.2)
inspec (1.1.0, 1.0.0)
kitchen-inspec (0.15.2)
```

Any ideas as to what to try next?
