### ISSUE TITLE
kitchen-inspec fails to configure HTTPS winrm for inspec

### ISSUE THREAD

**Issue by joekhoobyar** [chef/kitchen-inspec#152]
I have a _working_ configuration for test-kitchen that uses self-signed HTTPS winrm as a transport:

```yaml
---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  subnet_id: <%= ENV['SUBNET_ID'] %>
  security_group_ids: ["<%= ENV['SG_ID'] %>"]
  aws_ssh_key_id: <%= ENV['SSH_KEY'] %>
  iam_profile_name: <%= ENV['IAM_PROFILE'] %>
  associate_public_ip: <%= ENV['PUBLIC_IP'] %>
  ssl: true
  self_signed: true
  tags:
    Owner: <%= ENV['TAGS_OWNER'] %>
    Environment: <%= ENV['TAGS_ENVIRONMENT'] %>
    Project: <%= ENV['TAGS_PROJECT'] %>
    ExpirationDate: "<%= ENV['TAGS_EXPIRY'] %>"

transport:
  name: winrm
  username: Administrator
  ssh_key: <%= ENV['SSH_KEY_PATH'] %>
  port: 5986
  winrm_transport: ssl
  ssl: true
  self_signed: true

verifier:
  name: inspec

....
OMITTED FOR BREVITY
....
```

However, when kitchen-inspec prepares the [winrm runner_options](https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L238), it fails to pass the necessary information to allow inspec to utilize the HTTPS transport.

At a minimum, kitchen-inspec should apply the same defaults as test-kitchen, when encountering `winrm_transport: ssl`.  This means that it should configure `'ssl' => true, 'self_signed' => true` in winrm runner options whenever it detects `winrm_transport: ssl`.

I will raise a PR that fixes this issue.
