### ISSUE TITLE
Can't use Branch for verifier

### ISSUE THREAD

**Issue by anniehedgpeth** [chef/kitchen-inspec#157]
I'd like to use the `develop` branch for my tests in Test Kitchen, but when I use:

```
    verifier:
      inspec_tests: 
        - name: inspec-profile-name
          git: ssh://git@git.company.com:7999/project/inspec-repo.git
          branch: develop
```
..it still tests the master branch. The default branch of the repo is `develop`. 

I've tried it with the commit and version specified, as well, but it still uses master.

```
    verifier:
      inspec_tests: 
        - name: inspec-profile-name
          git: ssh://git@git.company.com:7999/project/inspec-repo.git
          branch: develop
          commit: c9876ekjhgacf376547654b6df6f47a945a0a098
          version: 0.2.8
```
```
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

My Jenkins agent is on ChefDK 2.3.4 and the branch DOES work.
