### ISSUE TITLE
Unable to use profile files

### ISSUE THREAD

**Issue by mmukherjee** [chef/kitchen-inspec#184]
Hi,

I am having an inspec profile with 'profile files' and am trying to execute it using 'test kitchen'. I end up with this error -

```
$ kitchen verify
-----> Starting Kitchen (v1.13.2)
-----> Verifying <default-centos-nightly>...
       Using `blh/blah/path` for testing
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined local variable or method `inspec' for #<#<Class:0x007fd1e6c87f48>:0x007fd1e6c872c8>] on default-centos-nightly
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The folder structure is like this -

![image](https://user-images.githubusercontent.com/1771188/40151690-8fda02b6-59d5-11e8-8826-9a2fb245aa81.png)

the control - 'common.rb' is -
```
my_packages = yaml(content: inspec.profile.file('packages.yml')).params
my_packages.each do |s|
  describe package(s['package_name']) do
    it { should be_installed }
  end
end
```

The .kitchen.yml has this -
```
suites:
  - name: default
    run_list:
      - recipe[chef_base_server::default]
    verifier:
      inspec_tests:
        - test/integration/
    attributes:
```

What am I missing/where am I going wrong?
