### ISSUE TITLE
Cannot run supermarket and compliance profiles

### ISSUE THREAD

**Issue by chris-rock** [chef/kitchen-inspec#80]
kitchen-inspec does not load supermarket urls

```
suites:
  - name: default
    run_list:
      - recipe[prepare]
    verifier:
      inspec_tests:
        - supermarket://hardening/ssh-hardening
```
