### ISSUE TITLE
Kitchen verify fails with the kitchen-docker plugin

### ISSUE THREAD

**Issue by brentm5** [chef/kitchen-inspec#83]
Not sure if this is an issue with kitchen-docker or kitchen-inspec.  The issue returned comes with the following:

```
       Search `/Users/user/code/cookbook/test/integration/default` for tests
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [Sudo failed: Sudo requires a TTY. Please see the README on how to configure sudo to allow for non-interactive usage.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The kitchen file looks a such and the converge works easily.  I am also using docker-beta which I am not sure if that plays into this at all.

```

---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[cookbook]
```
